/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.compilatore_re;

import it.unicam.cs.compilatore_re.gen.ReFollowedByListLexer;
import it.unicam.cs.compilatore_re.gen.ReFollowedByListParser;
import it.unicam.cs.compilatore_re.semantic_analysis.ThompsonNFAEvalVisitor;
import it.unicam.cs.compilatore_re.semantic_analysis.ThompsonNFASynthAttr;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

import java.io.IOException;

public class ThompsonNFARunner {

    public static void main(String[] args) throws IOException {
        CharStream input = CharStreams.fromStream(System.in);
        ReFollowedByListLexer lexer = new ReFollowedByListLexer(input);
        CommonTokenStream commonTokenStream = new CommonTokenStream(lexer);
        ReFollowedByListParser parser = new ReFollowedByListParser(commonTokenStream);
        ParseTree parseTree = parser.s();

         ThompsonNFAEvalVisitor visitor= new ThompsonNFAEvalVisitor();
        ThompsonNFASynthAttr a = visitor.visit(parseTree);
        System.out.println(a.getResult());
    }
}
