/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.compilatore_re;

import org.junit.Test;
import static org.junit.Assert.*;

public class ThompsonNFARunnerTest {
    @Test public void testAppHasAGreeting() {
        ThompsonNFARunner classUnderTest = new ThompsonNFARunner();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
